// Code generated by "stringer -type=Op"; DO NOT EDIT.

package dectest

import "strconv"

const _Op_name = "AddDivSubApplyAbsClassCmpCopyCopySignQuoIntFMALogLog10MaxMinNegMulPowQuantizeReduceRemShiftRoundToIntSqrt"

var _Op_index = [...]uint8{0, 3, 6, 9, 14, 17, 22, 25, 29, 37, 43, 46, 49, 54, 57, 60, 63, 66, 69, 77, 83, 86, 91, 101, 105}

func (i Op) String() string {
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
